FROM python:3.7-alpine
RUN apk add build-base
RUN pip install pep8==1.7.1
RUN pip install pyflakes==2.1.1
RUN pip install pylint==2.4.4
RUN pip install prospector==1.2.0
RUN pip install bandit==1.6.2
